project:
  type: website
  output-dir: docs 
  render:
  - "index.qmd"
  - "!forest.qmd"
  - "!dash/comp.qmd"

website:
  title: "Isometric Model Analysis"
  search: true
  navbar:
    logo: "./www/logo.png"
    left:
      - text: "Project ReGAIN"
        href: index.qmd

format:
  html:
    css: styles.css
    code-fold: true





